### ISSUE TITLE
How use image 

### ISSUE THREAD

**Issue by rafaelgfirmino** [Equanox/gotron#18] opened 2018-12-23 21:00 UTC
Hi, 
How to use image in this package, because the image not load. I'm  use vuejs. 
can you put image in gotron's example?

**Comment by Equanox** [comment] 2018-12-24 10:36
To use a image it must be included in the directory given to `gotron.New("webapp")` and referenced using a relative path to `webapp`. Everything in `webapp` is exposed by a fileserver when given to electron.

```
webapp/
  img/
    img.png
  index.html
```
In `index.html` (or some imported js code) reference your img like this..
```
 <img src="img/img.png"></img>
```
     

If you are using `example/main.go` put your image inside `example/ui/build` or use your own directory containing your application.

**Comment by rafaelgfirmino** [comment] 2018-12-24 22:50
I'm Using vuecli3 when I put in my components in src/views/Home.vue  I can't call the images using this annotations
```html   
<img alt="Vue logo" src="@/assets/logo.png"> don't work
<img alt="Vue logo" src="../assets/logo.png"> don't work 
```
But if I put the image in src/app.vue  using this form import  it's work
```html  
<img alt="Vue logo" src="@/assets/logo.png"> work
<img alt="Vue logo" src="../assets/logo.png">  work 
```

**Comment by Equanox** [comment] 2018-12-25 09:34
I'm not too familiar with vue. Guess this related to the way you build your project? Are other components in Home.vue displayed correctly?

Can provide a complete example?

**Comment by rafaelgfirmino** [comment] 2018-12-25 12:27
**Guess this related to the way you build your project?**
Yes, but in pure vue it's work
**Are other components in Home.vue displayed correctly?**
Yes, other things running correctly 
**Can provide a complete example?**
https://github.com/rafaelgfirmino/gotron-vue

 You can see the file src/App.vue where I call the image and it come correctly. 
 The problem is when I call the image in src/components/Home.vue.

**Comment by puengel** [comment] 2018-12-25 13:20
I just took your example and followed the steps you provided. This is what I see after running `go run main.go`:

![image](https://user-images.githubusercontent.com/40580839/50423019-1721ae80-0850-11e9-825d-8bc9a5070d1a.png)

**Comment by rafaelgfirmino** [comment] 2018-12-25 13:59
Sorry, @puengel  you need click in home for where is the wrong image.

**Comment by puengel** [comment] 2018-12-27 15:03
Hey @rafaelgfirmino , I found the cause of your problem.
https://github.com/rafaelgfirmino/gotron-vue/blob/master/src/router.js line 8:
`mode: 'home',`
 should not be used in electron apps. If you remove this line your code works just fine.
![grafik](https://user-images.githubusercontent.com/40580839/50484450-d57c3980-09f0-11e9-9756-13f33d4c8c2e.png)

Closing this issue as it is not a gotron issue.

**Closed as completed by puengel** 2018-12-27 15:03 UTC

**Comment by rafaelgfirmino** [comment] 2018-12-28 12:15
Thanks man !
